name = "zuzalu-updater"
main = "src/index.ts"
compatibility_date = "2023-04-23"

[triggers]
# Every minute
crons = ["0 */2 * * *"]


[vars]
CONTRACT_ADDRESS = "0x9E9e9995f83975770C454be031C1E68bF24dC0af"
