name = "zuzalu-updater"
main = "src/index.ts"
node_compat = true
compatibility_date = "2023-04-23"

[triggers]
# Every minute
crons = [ "* * * * *" ]


[vars]
CONTRACT_ADDRESS="0x275887D2D22d471663D58d69b9611792fFf1FEeD"
